name: Go

on:
  push:
    branches: [ without-test-files ]
  pull_request:
    branches: [ without-test-files ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Using linter for go code
      run : make docker-lint

    # - name: Build
    #   run: go build 
